POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "SaimonSeiz",
  "password": "awebo"
}

### Another user
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "wele_milana",
  "password": "secretito"
}