### Posting a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Ejemplificando el ejemplo",
  "author": "",
  "url": "http://example.com/new-blog-post",
  "likes": 5
}

### Posting a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "SaimonSeiz",
  "name": "Rudy Simón",
  "password": "awebo"
}