### Posting a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Ejemplificando el ejemplo",
  "author": "",
  "url": "http://example.com/new-blog-post",
  "likes": 5
}

### Posting a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "SaimonSeiz",
  "name": "Rudy Simón",
  "password": "awebo"
}

### Posting a new blog with user token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndlbGVfbWlsYW5hIiwiaWQiOiI2ODc2YzhiMTkyYWJjODYzN2IyMzRjOTkiLCJpYXQiOjE3NTI2NzAxNzYsImV4cCI6MTc1MjY3NzM3Nn0.FPXyaX3QBwH1ejE_wtTOaStYXEh9k7jWrsl58Fn0dto

{
  "title": "Ejemplificando el ejemplo",
  "author": "",
  "url": "http://example.com/new-blog-post",
  "likes": 5
}